auth:
  jwt:
    secret: 915d2e1f1bf56fa2185f1092d3102d46f90905f6632d2b4b7c84bdf7f5bf62f6
    expiration: 3600000 #IN MILLISECONDS
cookie:
  name: property-hub
  domain: localhost
  secure: true
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/property-hub
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8086